name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up MSVC developer environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install WiX Toolset
      run: dotnet tool install --global wix

    - name: Configure CMake
      run: >
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64

    - name: Build all targets and package
      run: >
        cmake --build build --config Release --target package_msi

    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI-Traffic-Interceptor-MSI
        path: build/AIInterceptor.msi 