name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up MSVC developer environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DENABLE_NATIVE_TESTS=OFF

    - name: Build C++ components
      run: |
        cmake --build build --config Release --target ai_injector
        cmake --build build --config Release --target ai_hook
        cmake --build build --config Release --target dll_diag
        cmake --build build --config Release --target copy_config
        cmake --build build --config Release --target copy_preload

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build C# Collector
      run: |
        dotnet build collector/Collector.csproj -c Release

    - name: Build C# Proxy
      run: |
        dotnet build proxy/Proxy.csproj -c Release

    - name: Install WiX Toolset
      shell: pwsh
      run: |
        dotnet tool install --global wix
        # Add .NET tools to PATH for current and future steps
        echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build package
      shell: pwsh
      run: |
        # Ensure WiX is in PATH for this step
        $env:PATH = "$env:USERPROFILE\.dotnet\tools;$env:PATH"
        # Reconfigure to detect WiX
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DENABLE_NATIVE_TESTS=OFF
        # Build package
        cmake --build build --config Release --target package_msi

    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: AI-Traffic-Interceptor-MSI
        path: build/AIInterceptor.msi 